package com.mightykatun.speedometer.app.domain.model

data class SpeedEstimatorConfig(
    val minimumSpeedAccuracyMetersPerSecond: Double = 0.2,
    val missingSpeedAccuracyMetersPerSecond: Double = 2.0,
    val maximumSpeedAccuracyMetersPerSecond: Double = 3.0,
    val speedAccuracyInflation: Double = 1.5,
    val innovationGate: Double = 10.83,
    val velocityProcessNoise: Double = 0.25,
    val fallbackVelocityProcessNoise: Double = 1.0,
    val biasRandomWalkNoise: Double = 0.0009,
    val initialBiasVariance: Double = 0.25,
    val maximumAccelerationMetersPerSecondSquared: Double = 15.0,
    val maximumInertialStepNanos: Long = 100_000_000L,
    val maximumOrientationAgeNanos: Long = 100_000_000L,
    val maximumCourseAgeNanos: Long = 2_000_000_000L,
    val trackingAgeNanos: Long = 2_000_000_000L,
    val unavailableAgeNanos: Long = 3_000_000_000L,
    val replayHistoryNanos: Long = 5_000_000_000L,
    val maximumDelayedGnssNanos: Long = 3_000_000_000L,
    val minimumCourseSpeedMetersPerSecond: Double = 2.0,
    val legacyMinimumCourseSpeedMetersPerSecond: Double = 5.0,
    val maximumCourseHorizontalAccuracyMeters: Double = 25.0,
    val legacyMaximumCourseHorizontalAccuracyMeters: Double = 15.0,
    val maximumBearingAccuracyDegrees: Double = 20.0,
    val maximumLegacyBearingDeltaDegrees: Double = 12.0,
    val maximumTrackingTwoSigmaMetersPerSecond: Double = 1.0,
    val stationarySpeedMetersPerSecond: Double = 0.0,
    val stationarySpeedAccuracyMetersPerSecond: Double = 0.15,
    val stationaryRequiredFixes: Int = 3,
    val stationaryDwellNanos: Long = 2_000_000_000L,
    val stationaryAccelerationMetersPerSecondSquared: Double = 0.15,
    val stationaryExitAccelerationMetersPerSecondSquared: Double = 0.25,
    val stationaryExitDwellNanos: Long = 200_000_000L,
    val zeroVelocityVariance: Double = 0.0025
)
